/**
 * The role hierarchy, highest first. See src/lib/permissions.ts for what each
 * one may do, and supabase/migrations/0001_closed_access_rbac.sql for the
 * database-side grants that actually enforce it.
 */
export type Role = 'super_admin' | 'admin' | 'manager' | 'staff' | 'viewer'

export type UserStatus = 'active' | 'inactive' | 'pending'

export type Stage =
  | 'lead'
  | 'contacted'
  | 'site_visit'
  | 'proposal_sent'
  | 'negotiation'
  | 'won'
  | 'lost'

export type VisitStatus = 'scheduled' | 'completed' | 'cancelled'
export type AppointmentKind = 'site_visit' | 'meeting'

export type Relationship =
  | 'new'
  | 'existing_partner'
  | 'works_zondela'
  | 'dormant'
  | 'not_interested'

export type MainMarket =
  | 'arusha'
  | 'dar_es_salaam'
  | 'dodoma'
  | 'mwanza'
  | 'zanzibar'
  | 'tanzania'
  | 'east_africa'
  | 'international'
export type FollowUpStatus = 'pending' | 'done' | 'skipped'
export type TemplateCategory = 'general' | 'pricing' | 'follow_up' | 'proposal'
export type Channel = 'email' | 'whatsapp'
export type AgreementStatus = 'draft' | 'sent' | 'accepted' | 'declined'

export interface Profile {
  id: string
  full_name: string
  email: string
  phone_number: string | null
  role: Role
  /**
   * `pending` until the invitation is accepted and a password is set;
   * `inactive` locks the account out without deleting its history.
   */
  status: UserStatus
  /** Who invited them, when the account came from Admin → Users. */
  invited_by: string | null
  last_login: string | null
  created_at: string
  updated_at: string
}

/**
 * One entry in the audit trail. Names and roles are snapshots taken when the
 * action happened, so the line still reads correctly after an account is
 * deleted and performed_by/target_user have nulled out.
 */
export interface ActivityLog {
  id: string
  performed_by: string | null
  performed_by_name: string | null
  performed_by_role: Role | null
  action: string
  target_user: string | null
  target_user_name: string | null
  previous_value: string | null
  new_value: string | null
  details: Record<string, unknown> | null
  created_at: string
}

export interface PermissionRow {
  key: string
  label: string
  description: string
  category: string
  sort_order: number
}

export interface RolePermissionRow {
  role: Role
  permission: string
}

export interface Company {
  id: string
  name: string
  website: string | null
  address: string | null
  country: string | null
  relationship: Relationship | null
  main_market: MainMarket | null
  stage: Stage
  notes: string | null
  owner_id: string | null
  /** A rep with no login. owner_id, not this, governs visibility. */
  owner_name: string | null
  created_at: string
  updated_at: string
}

export interface Contact {
  id: string
  company_id: string
  full_name: string
  job_title: string | null
  email: string | null
  phone: string | null
  whatsapp: string | null
  is_primary: boolean
  created_at: string
}

export interface SiteVisit {
  id: string
  company_id: string
  contact_id: string | null
  rep_id: string | null
  /** A rep with no login; set instead of rep_id, never as well as. */
  rep_name: string | null
  kind: AppointmentKind
  scheduled_for: string
  status: VisitStatus
  summary: string | null
  created_at: string
}

export interface FollowUp {
  id: string
  company_id: string
  contact_id: string | null
  assigned_to: string | null
  /** A rep with no login; set instead of assigned_to, never as well as. */
  assigned_name: string | null
  due_at: string
  note: string
  status: FollowUpStatus
  created_at: string
}

export interface StoRateCardItem {
  id: string
  service_name: string
  description: string | null
  price: number
  currency: string
  unit: string | null
  active: boolean
  sort_order: number
  created_at: string
}

export interface StoAgreement {
  id: string
  /** Generated by the database: STO-0001, STO-0002, … */
  reference: string
  company_id: string
  contact_id: string | null
  title: string
  status: AgreementStatus
  currency: string
  discount_percent: number
  starts_on: string | null
  valid_until: string | null
  terms: string | null
  notes: string | null
  sent_at: string | null
  accepted_at: string | null
  declined_at: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

/**
 * One priced line on an agreement.
 *
 * The service name, price and unit are copied from the rate card rather than
 * looked up through rate_card_item_id, so repricing a service later cannot
 * rewrite an agreement a client has already accepted.
 */
export interface StoAgreementItem {
  id: string
  agreement_id: string
  rate_card_item_id: string | null
  service_name: string
  description: string | null
  unit: string | null
  quantity: number
  unit_price: number
  sort_order: number
}

/** What the agreement pages work with: the header plus its priced lines. */
export interface StoAgreementWithItems extends StoAgreement {
  items: StoAgreementItem[]
}

export interface EmailTemplate {
  id: string
  name: string
  subject: string
  body_html: string
  category: TemplateCategory
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface PricingDocument {
  id: string
  name: string
  /** Key into the `pricing` storage bucket, not a URL. */
  storage_path: string
  size_bytes: number
  is_default: boolean
  uploaded_by: string | null
  created_at: string
}

/**
 * Where an outgoing message got to.
 *
 * `sent` is the furthest the app can know on its own — it hands off to a mail
 * client or WhatsApp, and neither reports back. `delivered`, `viewed` and
 * `failed` are marked by whoever sent it (or by an email provider, once one is
 * wired up); `approved` and `rejected` follow the agreement's own status.
 */
export type MessageStatus =
  | 'queued'
  | 'sent'
  | 'delivered'
  | 'viewed'
  | 'failed'
  | 'approved'
  | 'rejected'

export interface SentMessage {
  id: string
  company_id: string | null
  contact_id: string | null
  /** The agreement this went out with, when it was sent from STO. */
  agreement_id: string | null
  sent_by: string | null
  channel: Channel
  template_id: string | null
  subject: string | null
  body: string
  to_name: string | null
  to_email: string | null
  status: MessageStatus
  delivered_at: string | null
  viewed_at: string | null
  failed_at: string | null
  responded_at: string | null
  failure_reason: string | null
  status_note: string | null
  /** Set by an email provider, so its webhooks can find this row again. */
  provider: string | null
  provider_message_id: string | null
  sent_at: string
  updated_at: string
}

/**
 * The letterhead: one row, read by the agreement document, the send modal and
 * the email signature. Rebranding is this form rather than a search for
 * hardcoded strings.
 */
export interface OrgSettings {
  id: number
  org_name: string
  legal_name: string | null
  tagline: string | null
  address: string | null
  city: string | null
  country: string | null
  phone: string | null
  email: string | null
  website: string | null
  logo_url: string | null
  /** Plain hex — inline styles are the only styling an email client honours. */
  brand_color: string
  accent_color: string
  agreement_intro: string | null
  agreement_terms_default: string | null
  agreement_footer: string | null
  signatory_name: string | null
  signatory_title: string | null
  email_from_name: string | null
  email_from_address: string | null
  email_reply_to: string | null
  email_bcc: string | null
  email_signature: string | null
  created_at: string
  updated_at: string
}

// Minimal Supabase Database type. Since we're not using generated types
// (no CLI access assumed), this keeps the client typed loosely but usably.
// Run `supabase gen types typescript` later for full type safety.
export interface Database {
  public: {
    Tables: {
      profiles: { Row: Profile; Insert: Partial<Profile>; Update: Partial<Profile> }
      companies: { Row: Company; Insert: Partial<Company>; Update: Partial<Company> }
      contacts: { Row: Contact; Insert: Partial<Contact>; Update: Partial<Contact> }
      site_visits: { Row: SiteVisit; Insert: Partial<SiteVisit>; Update: Partial<SiteVisit> }
      follow_ups: { Row: FollowUp; Insert: Partial<FollowUp>; Update: Partial<FollowUp> }
      sto_rate_card: {
        Row: StoRateCardItem
        Insert: Partial<StoRateCardItem>
        Update: Partial<StoRateCardItem>
      }
      sto_agreements: {
        Row: StoAgreement
        Insert: Partial<StoAgreement>
        Update: Partial<StoAgreement>
      }
      sto_agreement_items: {
        Row: StoAgreementItem
        Insert: Partial<StoAgreementItem>
        Update: Partial<StoAgreementItem>
      }
      email_templates: {
        Row: EmailTemplate
        Insert: Partial<EmailTemplate>
        Update: Partial<EmailTemplate>
      }
      pricing_documents: {
        Row: PricingDocument
        Insert: Partial<PricingDocument>
        Update: Partial<PricingDocument>
      }
      sent_messages: {
        Row: SentMessage
        Insert: Partial<SentMessage>
        Update: Partial<SentMessage>
      }
      activity_logs: {
        Row: ActivityLog
        Insert: Partial<ActivityLog>
        Update: Partial<ActivityLog>
      }
      permissions: {
        Row: PermissionRow
        Insert: Partial<PermissionRow>
        Update: Partial<PermissionRow>
      }
      role_permissions: {
        Row: RolePermissionRow
        Insert: Partial<RolePermissionRow>
        Update: Partial<RolePermissionRow>
      }
      org_settings: {
        Row: OrgSettings
        Insert: Partial<OrgSettings>
        Update: Partial<OrgSettings>
      }
    }
  }
}

export const STAGE_LABELS: Record<Stage, string> = {
  lead: 'Lead',
  contacted: 'Contacted',
  site_visit: 'Site visit',
  proposal_sent: 'Proposal sent',
  negotiation: 'Negotiation',
  won: 'Won',
  lost: 'Lost',
}

export const STAGE_ORDER: Stage[] = [
  'lead',
  'contacted',
  'site_visit',
  'proposal_sent',
  'negotiation',
  'won',
  'lost',
]
