export type Role = 'owner' | 'marketing'

export type Stage =
  | 'lead'
  | 'contacted'
  | 'site_visit'
  | 'proposal_sent'
  | 'negotiation'
  | 'won'
  | 'lost'

export type VisitStatus = 'scheduled' | 'completed' | 'cancelled'
export type AppointmentKind = 'site_visit' | 'meeting'

export type Relationship =
  | 'new'
  | 'existing_partner'
  | 'works_zondela'
  | 'dormant'
  | 'not_interested'

export type MainMarket =
  | 'arusha'
  | 'dar_es_salaam'
  | 'dodoma'
  | 'mwanza'
  | 'zanzibar'
  | 'tanzania'
  | 'east_africa'
  | 'international'
export type FollowUpStatus = 'pending' | 'done' | 'skipped'
export type TemplateCategory = 'general' | 'pricing' | 'follow_up' | 'proposal'
export type Channel = 'email' | 'whatsapp'
export type AgreementStatus = 'draft' | 'sent' | 'accepted' | 'declined'

export interface Profile {
  id: string
  full_name: string
  email: string
  role: Role
  created_at: string
}

export interface Company {
  id: string
  name: string
  website: string | null
  address: string | null
  country: string | null
  relationship: Relationship | null
  main_market: MainMarket | null
  stage: Stage
  notes: string | null
  owner_id: string | null
  /** A rep with no login. owner_id, not this, governs visibility. */
  owner_name: string | null
  created_at: string
  updated_at: string
}

export interface Contact {
  id: string
  company_id: string
  full_name: string
  job_title: string | null
  email: string | null
  phone: string | null
  whatsapp: string | null
  is_primary: boolean
  created_at: string
}

export interface SiteVisit {
  id: string
  company_id: string
  contact_id: string | null
  rep_id: string | null
  /** A rep with no login; set instead of rep_id, never as well as. */
  rep_name: string | null
  kind: AppointmentKind
  scheduled_for: string
  status: VisitStatus
  summary: string | null
  created_at: string
}

export interface FollowUp {
  id: string
  company_id: string
  contact_id: string | null
  assigned_to: string | null
  /** A rep with no login; set instead of assigned_to, never as well as. */
  assigned_name: string | null
  due_at: string
  note: string
  status: FollowUpStatus
  created_at: string
}

export interface StoRateCardItem {
  id: string
  service_name: string
  description: string | null
  price: number
  currency: string
  unit: string | null
  active: boolean
  sort_order: number
  created_at: string
}

export interface StoAgreement {
  id: string
  /** Generated by the database: STO-0001, STO-0002, … */
  reference: string
  company_id: string
  contact_id: string | null
  title: string
  status: AgreementStatus
  currency: string
  discount_percent: number
  starts_on: string | null
  valid_until: string | null
  terms: string | null
  notes: string | null
  sent_at: string | null
  accepted_at: string | null
  declined_at: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

/**
 * One priced line on an agreement.
 *
 * The service name, price and unit are copied from the rate card rather than
 * looked up through rate_card_item_id, so repricing a service later cannot
 * rewrite an agreement a client has already accepted.
 */
export interface StoAgreementItem {
  id: string
  agreement_id: string
  rate_card_item_id: string | null
  service_name: string
  description: string | null
  unit: string | null
  quantity: number
  unit_price: number
  sort_order: number
}

/** What the agreement pages work with: the header plus its priced lines. */
export interface StoAgreementWithItems extends StoAgreement {
  items: StoAgreementItem[]
}

export interface EmailTemplate {
  id: string
  name: string
  subject: string
  body_html: string
  category: TemplateCategory
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface PricingDocument {
  id: string
  name: string
  /** Key into the `pricing` storage bucket, not a URL. */
  storage_path: string
  size_bytes: number
  is_default: boolean
  uploaded_by: string | null
  created_at: string
}

export interface SentMessage {
  id: string
  company_id: string | null
  contact_id: string | null
  sent_by: string | null
  channel: Channel
  template_id: string | null
  subject: string | null
  body: string
  sent_at: string
}

// Minimal Supabase Database type. Since we're not using generated types
// (no CLI access assumed), this keeps the client typed loosely but usably.
// Run `supabase gen types typescript` later for full type safety.
export interface Database {
  public: {
    Tables: {
      profiles: { Row: Profile; Insert: Partial<Profile>; Update: Partial<Profile> }
      companies: { Row: Company; Insert: Partial<Company>; Update: Partial<Company> }
      contacts: { Row: Contact; Insert: Partial<Contact>; Update: Partial<Contact> }
      site_visits: { Row: SiteVisit; Insert: Partial<SiteVisit>; Update: Partial<SiteVisit> }
      follow_ups: { Row: FollowUp; Insert: Partial<FollowUp>; Update: Partial<FollowUp> }
      sto_rate_card: {
        Row: StoRateCardItem
        Insert: Partial<StoRateCardItem>
        Update: Partial<StoRateCardItem>
      }
      sto_agreements: {
        Row: StoAgreement
        Insert: Partial<StoAgreement>
        Update: Partial<StoAgreement>
      }
      sto_agreement_items: {
        Row: StoAgreementItem
        Insert: Partial<StoAgreementItem>
        Update: Partial<StoAgreementItem>
      }
      email_templates: {
        Row: EmailTemplate
        Insert: Partial<EmailTemplate>
        Update: Partial<EmailTemplate>
      }
      pricing_documents: {
        Row: PricingDocument
        Insert: Partial<PricingDocument>
        Update: Partial<PricingDocument>
      }
      sent_messages: {
        Row: SentMessage
        Insert: Partial<SentMessage>
        Update: Partial<SentMessage>
      }
    }
  }
}

export const STAGE_LABELS: Record<Stage, string> = {
  lead: 'Lead',
  contacted: 'Contacted',
  site_visit: 'Site visit',
  proposal_sent: 'Proposal sent',
  negotiation: 'Negotiation',
  won: 'Won',
  lost: 'Lost',
}

export const STAGE_ORDER: Stage[] = [
  'lead',
  'contacted',
  'site_visit',
  'proposal_sent',
  'negotiation',
  'won',
  'lost',
]
