/**
 * The role hierarchy, highest first. See src/lib/permissions.ts for what each
 * one may do, and supabase/migrations/0001_closed_access_rbac.sql for the
 * database-side grants that actually enforce it.
 */
export type Role = 'super_admin' | 'admin' | 'manager' | 'staff' | 'viewer'

export type UserStatus = 'active' | 'inactive' | 'pending'

export type Stage =
  | 'lead'
  | 'contacted'
  | 'site_visit'
  | 'proposal_sent'
  | 'negotiation'
  | 'won'
  | 'lost'

export type VisitStatus = 'scheduled' | 'completed' | 'cancelled'
export type AppointmentKind = 'site_visit' | 'meeting'

export type Relationship =
  | 'new'
  | 'existing_partner'
  | 'works_zondela'
  | 'dormant'
  | 'not_interested'

export type MainMarket =
  | 'arusha'
  | 'dar_es_salaam'
  | 'dodoma'
  | 'mwanza'
  | 'zanzibar'
  | 'tanzania'
  | 'east_africa'
  | 'international'
export type FollowUpStatus = 'pending' | 'done' | 'skipped'
export type TemplateCategory = 'general' | 'pricing' | 'follow_up' | 'proposal'
export type Channel = 'email' | 'whatsapp'
export type AgreementStatus = 'draft' | 'sent' | 'accepted' | 'declined'

export interface Profile {
  id: string
  full_name: string
  email: string
  phone_number: string | null
  role: Role
  /**
   * `pending` until the invitation is accepted and a password is set;
   * `inactive` locks the account out without deleting its history.
   */
  status: UserStatus
  /** Who invited them, when the account came from Admin → Users. */
  invited_by: string | null
  last_login: string | null
  created_at: string
  updated_at: string
}

/**
 * One entry in the audit trail. Names and roles are snapshots taken when the
 * action happened, so the line still reads correctly after an account is
 * deleted and performed_by/target_user have nulled out.
 */
export interface ActivityLog {
  id: string
  performed_by: string | null
  performed_by_name: string | null
  performed_by_role: Role | null
  action: string
  target_user: string | null
  target_user_name: string | null
  previous_value: string | null
  new_value: string | null
  details: Record<string, unknown> | null
  created_at: string
}

export interface PermissionRow {
  key: string
  label: string
  description: string
  category: string
  sort_order: number
}

export interface RolePermissionRow {
  role: Role
  permission: string
}

export interface Company {
  id: string
  name: string
  website: string | null
  address: string | null
  country: string | null
  relationship: Relationship | null
  main_market: MainMarket | null
  stage: Stage
  notes: string | null
  owner_id: string | null
  /** A rep with no login. owner_id, not this, governs visibility. */
  owner_name: string | null
  created_at: string
  updated_at: string
}

export interface Contact {
  id: string
  company_id: string
  full_name: string
  job_title: string | null
  email: string | null
  phone: string | null
  whatsapp: string | null
  is_primary: boolean
  created_at: string
}

export interface SiteVisit {
  id: string
  company_id: string
  contact_id: string | null
  rep_id: string | null
  /** A rep with no login; set instead of rep_id, never as well as. */
  rep_name: string | null
  kind: AppointmentKind
  scheduled_for: string
  status: VisitStatus
  summary: string | null
  created_at: string
}

export interface FollowUp {
  id: string
  company_id: string
  contact_id: string | null
  assigned_to: string | null
  /** A rep with no login; set instead of assigned_to, never as well as. */
  assigned_name: string | null
  due_at: string
  note: string
  status: FollowUpStatus
  created_at: string
}

export interface StoRateCardItem {
  id: string
  service_name: string
  description: string | null
  price: number
  currency: string
  unit: string | null
  active: boolean
  sort_order: number
  created_at: string
}

export interface StoAgreement {
  id: string
  /** Generated by the database: STO-0001, STO-0002, … */
  reference: string
  company_id: string
  contact_id: string | null
  title: string
  status: AgreementStatus
  currency: string
  discount_percent: number
  starts_on: string | null
  valid_until: string | null
  terms: string | null
  notes: string | null
  sent_at: string | null
  accepted_at: string | null
  declined_at: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

/**
 * One priced line on an agreement.
 *
 * The service name, price and unit are copied from the rate card rather than
 * looked up through rate_card_item_id, so repricing a service later cannot
 * rewrite an agreement a client has already accepted.
 */
export interface StoAgreementItem {
  id: string
  agreement_id: string
  rate_card_item_id: string | null
  service_name: string
  description: string | null
  unit: string | null
  quantity: number
  unit_price: number
  sort_order: number
}

/** What the agreement pages work with: the header plus its priced lines. */
export interface StoAgreementWithItems extends StoAgreement {
  items: StoAgreementItem[]
}

/* ===========================================================================
   STO rate agreements
   ---------------------------------------------------------------------------
   What Zondela sends an operator is the season's rate sheet for Zondela House,
   not a priced quote: one version a year, sent to many operators, accepted by
   each. See supabase/migrations/0003_sto_rate_agreements.sql.
   =========================================================================== */

export type VersionStatus = 'draft' | 'active' | 'archived'
export type SendStatus = 'sent' | 'viewed' | 'accepted' | 'declined'

/**
 * One room type on the rates chart.
 *
 * Three prices, not one: the contract quotes every room at bed & breakfast,
 * half board and full board at once, and an operator picks per booking. The
 * occupancy is part of the rate — "Family Room, 340, sleeps 4" is the offer.
 */
export interface StoVersionRate {
  id: string
  version_id: string
  /** The room category this line belongs to, when the contract is divided. */
  section_id: string | null
  /** Free text — a season gets renamed more often than a schema should move. */
  season: string
  room_type: string
  description: string | null
  /** How many people the price covers. A Suite at 2 and at 4 are two lines. */
  pax: number
  /** The contracted rate at each meal plan. Per room, per night. */
  bb_price: number
  hb_price: number
  fb_price: number
  /** The published rate beside it — operators check the gap. */
  bb_rack: number
  hb_rack: number
  fb_rack: number
  max_occupancy: number
  currency: string
  sort_order: number
}

/** Priced per person alongside the room: lunch, dinner. */
export interface StoVersionSupplement {
  id: string
  version_id: string
  name: string
  description: string | null
  price: number
  currency: string
  unit: string
  sort_order: number
}

/**
 * One named clause of the contract — Meal Plan, Children Policy, Cancellation.
 *
 * Rows rather than one block of terms: the document numbers them, and each is
 * renegotiated on its own between seasons.
 */
export interface StoVersionTerm {
  id: string
  version_id: string
  title: string
  /** Blank-line separated. Lines opening with •, - or * render as a list. */
  body: string
  sort_order: number
}

/** One photograph on a room category. Key into the `sto` bucket. */
export interface StoSectionImage {
  id: string
  section_id: string
  storage_path: string
  caption: string | null
  sort_order: number
}

/**
 * A room category as the contract sets it out: Standard, Deluxe.
 *
 * Zondela House is one property, so what a contract divides into is its room
 * categories — they read differently to an operator, photograph differently
 * and price differently.
 */
export interface StoPropertySection {
  id: string
  version_id: string
  name: string
  description: string | null
  /** The full album, for operators who want more than the three shown. */
  gallery_url: string | null
  meal_plan_notes: string | null
  seasonal_notes: string | null
  /** Never printed. The team's own reminders about this category. */
  internal_notes: string | null
  sort_order: number
}

export interface StoPropertySectionWithImages extends StoPropertySection {
  images: StoSectionImage[]
}

export interface StoAgreementVersion {
  id: string
  name: string
  /** The season the rates are for, which is not always the year they were published. */
  year: number
  status: VersionStatus
  valid_from: string | null
  valid_to: string | null
  /** One line, read in lists and reports. */
  summary: string | null
  /** What the operator reads above the rates — the property overview. */
  intro: string | null
  terms: string | null
  /** How the chart is read: "Per room, per night". */
  rate_basis: string | null
  /** The line under the chart, about VAT and the tourism levy. */
  rates_note: string | null
  /** Never printed and never sent — where the negotiation is remembered. */
  internal_notes: string | null
  /** The uploaded rate sheet, exactly as supplied. Key into the `sto` bucket. */
  pdf_path: string | null
  pdf_name: string | null
  pdf_size_bytes: number
  created_by: string | null
  created_at: string
  updated_at: string
}

/** What the version pages work with: the header plus everything printed under it. */
export interface StoVersionWithRates extends StoAgreementVersion {
  rates: StoVersionRate[]
  supplements: StoVersionSupplement[]
  /** The room categories — Standard, Deluxe — with their photographs. */
  sections: StoPropertySectionWithImages[]
  /** The named clauses, in the order they are printed. */
  terms_list: StoVersionTerm[]
}

/** One operator, one version, and where it got to. */
export interface StoAgreementSend {
  id: string
  version_id: string
  company_id: string
  contact_id: string | null
  /** Copied at send time: it must stay true after the contact is edited. */
  to_name: string | null
  to_email: string | null
  /** What the emailed button points at. Never shown in the CRM's own URLs. */
  token: string
  status: SendStatus
  subject: string | null
  body: string | null
  /** The team's own note about this send. */
  note: string | null
  follow_up_at: string | null
  sent_by: string | null
  sent_at: string
  viewed_at: string | null
  accepted_at: string | null
  declined_at: string | null
  /** The signature block they filled in. No tax or registration details. */
  responded_name: string | null
  /** Signatory position/title, as the paper contract asks for. */
  responded_title: string | null
  responded_email: string | null
  responded_note: string | null
  created_at: string
  updated_at: string
}

export interface EmailTemplate {
  id: string
  name: string
  subject: string
  body_html: string
  category: TemplateCategory
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface PricingDocument {
  id: string
  name: string
  /** Key into the `pricing` storage bucket, not a URL. */
  storage_path: string
  size_bytes: number
  is_default: boolean
  uploaded_by: string | null
  created_at: string
}

/**
 * Where an outgoing message got to.
 *
 * `sent` is the furthest the app can know on its own — it hands off to a mail
 * client or WhatsApp, and neither reports back. `delivered`, `viewed` and
 * `failed` are marked by whoever sent it (or by an email provider, once one is
 * wired up); `approved` and `rejected` follow the agreement's own status.
 */
export type MessageStatus =
  | 'queued'
  | 'sent'
  | 'delivered'
  | 'viewed'
  | 'failed'
  | 'approved'
  | 'rejected'

export interface SentMessage {
  id: string
  company_id: string | null
  contact_id: string | null
  /** The agreement this went out with, when it was sent from STO. */
  agreement_id: string | null
  sent_by: string | null
  channel: Channel
  template_id: string | null
  subject: string | null
  body: string
  to_name: string | null
  to_email: string | null
  status: MessageStatus
  delivered_at: string | null
  viewed_at: string | null
  failed_at: string | null
  responded_at: string | null
  failure_reason: string | null
  status_note: string | null
  /** Set by an email provider, so its webhooks can find this row again. */
  provider: string | null
  provider_message_id: string | null
  sent_at: string
  updated_at: string
}

/**
 * The letterhead: one row, read by the agreement document, the send modal and
 * the email signature. Rebranding is this form rather than a search for
 * hardcoded strings.
 */
export interface OrgSettings {
  id: number
  org_name: string
  legal_name: string | null
  tagline: string | null
  address: string | null
  city: string | null
  country: string | null
  phone: string | null
  email: string | null
  website: string | null
  logo_url: string | null
  /** Plain hex — inline styles are the only styling an email client honours. */
  brand_color: string
  accent_color: string
  agreement_intro: string | null
  agreement_terms_default: string | null
  agreement_footer: string | null
  signatory_name: string | null
  signatory_title: string | null
  email_from_name: string | null
  email_from_address: string | null
  email_reply_to: string | null
  email_bcc: string | null
  email_signature: string | null
  created_at: string
  updated_at: string
}

// Minimal Supabase Database type. Since we're not using generated types
// (no CLI access assumed), this keeps the client typed loosely but usably.
// Run `supabase gen types typescript` later for full type safety.
export interface Database {
  public: {
    Tables: {
      profiles: { Row: Profile; Insert: Partial<Profile>; Update: Partial<Profile> }
      companies: { Row: Company; Insert: Partial<Company>; Update: Partial<Company> }
      contacts: { Row: Contact; Insert: Partial<Contact>; Update: Partial<Contact> }
      site_visits: { Row: SiteVisit; Insert: Partial<SiteVisit>; Update: Partial<SiteVisit> }
      follow_ups: { Row: FollowUp; Insert: Partial<FollowUp>; Update: Partial<FollowUp> }
      sto_rate_card: {
        Row: StoRateCardItem
        Insert: Partial<StoRateCardItem>
        Update: Partial<StoRateCardItem>
      }
      sto_agreements: {
        Row: StoAgreement
        Insert: Partial<StoAgreement>
        Update: Partial<StoAgreement>
      }
      sto_agreement_items: {
        Row: StoAgreementItem
        Insert: Partial<StoAgreementItem>
        Update: Partial<StoAgreementItem>
      }
      sto_agreement_versions: {
        Row: StoAgreementVersion
        Insert: Partial<StoAgreementVersion>
        Update: Partial<StoAgreementVersion>
      }
      sto_version_rates: {
        Row: StoVersionRate
        Insert: Partial<StoVersionRate>
        Update: Partial<StoVersionRate>
      }
      sto_version_supplements: {
        Row: StoVersionSupplement
        Insert: Partial<StoVersionSupplement>
        Update: Partial<StoVersionSupplement>
      }
      sto_version_terms: {
        Row: StoVersionTerm
        Insert: Partial<StoVersionTerm>
        Update: Partial<StoVersionTerm>
      }
      sto_version_property_sections: {
        Row: StoPropertySection
        Insert: Partial<StoPropertySection>
        Update: Partial<StoPropertySection>
      }
      sto_section_images: {
        Row: StoSectionImage
        Insert: Partial<StoSectionImage>
        Update: Partial<StoSectionImage>
      }
      sto_agreement_sends: {
        Row: StoAgreementSend
        Insert: Partial<StoAgreementSend>
        Update: Partial<StoAgreementSend>
      }
      email_templates: {
        Row: EmailTemplate
        Insert: Partial<EmailTemplate>
        Update: Partial<EmailTemplate>
      }
      pricing_documents: {
        Row: PricingDocument
        Insert: Partial<PricingDocument>
        Update: Partial<PricingDocument>
      }
      sent_messages: {
        Row: SentMessage
        Insert: Partial<SentMessage>
        Update: Partial<SentMessage>
      }
      activity_logs: {
        Row: ActivityLog
        Insert: Partial<ActivityLog>
        Update: Partial<ActivityLog>
      }
      permissions: {
        Row: PermissionRow
        Insert: Partial<PermissionRow>
        Update: Partial<PermissionRow>
      }
      role_permissions: {
        Row: RolePermissionRow
        Insert: Partial<RolePermissionRow>
        Update: Partial<RolePermissionRow>
      }
      org_settings: {
        Row: OrgSettings
        Insert: Partial<OrgSettings>
        Update: Partial<OrgSettings>
      }
    }
  }
}

export const STAGE_LABELS: Record<Stage, string> = {
  lead: 'Lead',
  contacted: 'Contacted',
  site_visit: 'Site visit',
  proposal_sent: 'Proposal sent',
  negotiation: 'Negotiation',
  won: 'Won',
  lost: 'Lost',
}

export const STAGE_ORDER: Stage[] = [
  'lead',
  'contacted',
  'site_visit',
  'proposal_sent',
  'negotiation',
  'won',
  'lost',
]
