/**
 * Folds the built preview into a single self-contained HTML fragment.
 *
 * Two constraints drive this: the artifact host applies a strict CSP that
 * blocks every external request (so the Google Fonts @import has to go, and
 * JS/CSS must be inline rather than linked), and it wraps the file in its own
 * <html>/<head>/<body>, so what we emit is a body fragment, not a document.
 */
import { readFile, writeFile, readdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const dist = fileURLToPath(new URL('../dist-preview', import.meta.url))
const files = await readdir(path.join(dist, 'assets'))

const jsFile = files.find((f) => f.endsWith('.js'))
const cssFile = files.find((f) => f.endsWith('.css'))
if (!jsFile) throw new Error('no JS bundle found in dist-preview/assets')

let js = await readFile(path.join(dist, 'assets', jsFile), 'utf8')
let css = cssFile ? await readFile(path.join(dist, 'assets', cssFile), 'utf8') : ''

// Locally embedded replacements for the blocked webfont import. Generated by
// preview/fetch-fonts.mjs; absent means the preview falls back to system-ui.
let fonts = ''
try {
  fonts = await readFile(fileURLToPath(new URL('./fonts.generated.css', import.meta.url)), 'utf8')
  console.log(`embedding ${(fonts.length / 1024).toFixed(0)} kB of webfonts`)
} catch {
  console.warn('fonts.generated.css missing — run `node preview/fetch-fonts.mjs` for real type')
}

// Remote font import would be blocked by CSP; the tokens in index.css already
// fall back to system-ui, so dropping it degrades cleanly.
// The pattern has to cover both `@import url('…')` and the bare `@import "…"`
// the CSS minifier rewrites it to, and must not stop at the first semicolon —
// the Google Fonts URL contains several inside its `family=` parameter.
const before = css.length
css = css.replace(/@import\s+(?:url\(\s*)?["']?https?:\/\/[^"')]+["']?\s*\)?\s*;/gi, '')
console.log(css.length !== before ? 'stripped remote @import from CSS' : 'no remote @import found')

if (/@import/i.test(css)) {
  throw new Error('CSS still contains an @import; it would be blocked by the artifact CSP')
}

// A literal </script> inside a string in the bundle would close the tag early.
js = js.replace(/<\/script/gi, '<\\/script')

const html = `<style>
${fonts}
${css}
</style>

<div id="root"></div>

<script type="module">
${js}
</script>
`

const out = path.join(dist, 'zondela-preview.html')
await writeFile(out, html, 'utf8')
console.log(`wrote ${out} (${(html.length / 1024).toFixed(0)} kB)`)
